# Home
GET http://localhost:3000/

###
# LISTA DE USUARIAOS

GET http://localhost:3000/users

###
# CADASTRO DE USUARIO

POST http://localhost:3000/users


###

PUT http://localhost:3000/users/45

###
# EXCLUSAO DE USUARIO
DELETE http://localhost:3000/users/45

###
# pedidos
GET http://localhost:3000/users/45/pedidos/3345KB
